/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScoringRouteImport } from './routes/scoring'
import { Route as PurposeRouteImport } from './routes/purpose'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as MyLeadsRouteImport } from './routes/my-leads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinkedinMessagesRouteImport } from './routes/linkedin-messages'
import { Route as LinkedinDashboardRouteImport } from './routes/linkedin-dashboard'
import { Route as ConsolidationScoringRouteImport } from './routes/consolidation-scoring'
import { Route as ConsolidationRouteImport } from './routes/consolidation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'
import { Route as ApiPublicInboundEmailRouteImport } from './routes/api/public/inbound-email'
import { Route as ApiPublicHooksRunDailySearchRouteImport } from './routes/api/public/hooks/run-daily-search'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoringRoute = ScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => rootRouteImport,
} as any)
const PurposeRoute = PurposeRouteImport.update({
  id: '/purpose',
  path: '/purpose',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLeadsRoute = MyLeadsRouteImport.update({
  id: '/my-leads',
  path: '/my-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinMessagesRoute = LinkedinMessagesRouteImport.update({
  id: '/linkedin-messages',
  path: '/linkedin-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinDashboardRoute = LinkedinDashboardRouteImport.update({
  id: '/linkedin-dashboard',
  path: '/linkedin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsolidationScoringRoute = ConsolidationScoringRouteImport.update({
  id: '/consolidation-scoring',
  path: '/consolidation-scoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsolidationRoute = ConsolidationRouteImport.update({
  id: '/consolidation',
  path: '/consolidation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInboundEmailRoute = ApiPublicInboundEmailRouteImport.update({
  id: '/api/public/inbound-email',
  path: '/api/public/inbound-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRunDailySearchRoute =
  ApiPublicHooksRunDailySearchRouteImport.update({
    id: '/api/public/hooks/run-daily-search',
    path: '/api/public/hooks/run-daily-search',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consolidation': typeof ConsolidationRoute
  '/consolidation-scoring': typeof ConsolidationScoringRoute
  '/linkedin-dashboard': typeof LinkedinDashboardRoute
  '/linkedin-messages': typeof LinkedinMessagesRoute
  '/login': typeof LoginRoute
  '/my-leads': typeof MyLeadsRoute
  '/pipeline': typeof PipelineRoute
  '/purpose': typeof PurposeRoute
  '/scoring': typeof ScoringRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/usage': typeof UsageRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/api/public/inbound-email': typeof ApiPublicInboundEmailRoute
  '/api/public/hooks/run-daily-search': typeof ApiPublicHooksRunDailySearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consolidation': typeof ConsolidationRoute
  '/consolidation-scoring': typeof ConsolidationScoringRoute
  '/linkedin-dashboard': typeof LinkedinDashboardRoute
  '/linkedin-messages': typeof LinkedinMessagesRoute
  '/login': typeof LoginRoute
  '/my-leads': typeof MyLeadsRoute
  '/pipeline': typeof PipelineRoute
  '/purpose': typeof PurposeRoute
  '/scoring': typeof ScoringRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/usage': typeof UsageRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/api/public/inbound-email': typeof ApiPublicInboundEmailRoute
  '/api/public/hooks/run-daily-search': typeof ApiPublicHooksRunDailySearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consolidation': typeof ConsolidationRoute
  '/consolidation-scoring': typeof ConsolidationScoringRoute
  '/linkedin-dashboard': typeof LinkedinDashboardRoute
  '/linkedin-messages': typeof LinkedinMessagesRoute
  '/login': typeof LoginRoute
  '/my-leads': typeof MyLeadsRoute
  '/pipeline': typeof PipelineRoute
  '/purpose': typeof PurposeRoute
  '/scoring': typeof ScoringRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/usage': typeof UsageRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/api/public/inbound-email': typeof ApiPublicInboundEmailRoute
  '/api/public/hooks/run-daily-search': typeof ApiPublicHooksRunDailySearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consolidation'
    | '/consolidation-scoring'
    | '/linkedin-dashboard'
    | '/linkedin-messages'
    | '/login'
    | '/my-leads'
    | '/pipeline'
    | '/purpose'
    | '/scoring'
    | '/settings'
    | '/sources'
    | '/usage'
    | '/leads/$leadId'
    | '/api/public/inbound-email'
    | '/api/public/hooks/run-daily-search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consolidation'
    | '/consolidation-scoring'
    | '/linkedin-dashboard'
    | '/linkedin-messages'
    | '/login'
    | '/my-leads'
    | '/pipeline'
    | '/purpose'
    | '/scoring'
    | '/settings'
    | '/sources'
    | '/usage'
    | '/leads/$leadId'
    | '/api/public/inbound-email'
    | '/api/public/hooks/run-daily-search'
  id:
    | '__root__'
    | '/'
    | '/consolidation'
    | '/consolidation-scoring'
    | '/linkedin-dashboard'
    | '/linkedin-messages'
    | '/login'
    | '/my-leads'
    | '/pipeline'
    | '/purpose'
    | '/scoring'
    | '/settings'
    | '/sources'
    | '/usage'
    | '/leads/$leadId'
    | '/api/public/inbound-email'
    | '/api/public/hooks/run-daily-search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsolidationRoute: typeof ConsolidationRoute
  ConsolidationScoringRoute: typeof ConsolidationScoringRoute
  LinkedinDashboardRoute: typeof LinkedinDashboardRoute
  LinkedinMessagesRoute: typeof LinkedinMessagesRoute
  LoginRoute: typeof LoginRoute
  MyLeadsRoute: typeof MyLeadsRoute
  PipelineRoute: typeof PipelineRoute
  PurposeRoute: typeof PurposeRoute
  ScoringRoute: typeof ScoringRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
  UsageRoute: typeof UsageRoute
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  ApiPublicInboundEmailRoute: typeof ApiPublicInboundEmailRoute
  ApiPublicHooksRunDailySearchRoute: typeof ApiPublicHooksRunDailySearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoring': {
      id: '/scoring'
      path: '/scoring'
      fullPath: '/scoring'
      preLoaderRoute: typeof ScoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purpose': {
      id: '/purpose'
      path: '/purpose'
      fullPath: '/purpose'
      preLoaderRoute: typeof PurposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-leads': {
      id: '/my-leads'
      path: '/my-leads'
      fullPath: '/my-leads'
      preLoaderRoute: typeof MyLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin-messages': {
      id: '/linkedin-messages'
      path: '/linkedin-messages'
      fullPath: '/linkedin-messages'
      preLoaderRoute: typeof LinkedinMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin-dashboard': {
      id: '/linkedin-dashboard'
      path: '/linkedin-dashboard'
      fullPath: '/linkedin-dashboard'
      preLoaderRoute: typeof LinkedinDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consolidation-scoring': {
      id: '/consolidation-scoring'
      path: '/consolidation-scoring'
      fullPath: '/consolidation-scoring'
      preLoaderRoute: typeof ConsolidationScoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consolidation': {
      id: '/consolidation'
      path: '/consolidation'
      fullPath: '/consolidation'
      preLoaderRoute: typeof ConsolidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inbound-email': {
      id: '/api/public/inbound-email'
      path: '/api/public/inbound-email'
      fullPath: '/api/public/inbound-email'
      preLoaderRoute: typeof ApiPublicInboundEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-daily-search': {
      id: '/api/public/hooks/run-daily-search'
      path: '/api/public/hooks/run-daily-search'
      fullPath: '/api/public/hooks/run-daily-search'
      preLoaderRoute: typeof ApiPublicHooksRunDailySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsolidationRoute: ConsolidationRoute,
  ConsolidationScoringRoute: ConsolidationScoringRoute,
  LinkedinDashboardRoute: LinkedinDashboardRoute,
  LinkedinMessagesRoute: LinkedinMessagesRoute,
  LoginRoute: LoginRoute,
  MyLeadsRoute: MyLeadsRoute,
  PipelineRoute: PipelineRoute,
  PurposeRoute: PurposeRoute,
  ScoringRoute: ScoringRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
  UsageRoute: UsageRoute,
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  ApiPublicInboundEmailRoute: ApiPublicInboundEmailRoute,
  ApiPublicHooksRunDailySearchRoute: ApiPublicHooksRunDailySearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
